[package]
name = "rchat"
version = "0.1.0"
authors = ["Yannic Rieger <riegeryannic@gmail.com>"]
edition = "2018"

[dependencies]
bytebuffer = "0.2.1"
byteorder = "1.3.1"
rust-crypto = "^0.2"
num-bigint = "0.2.2"